export const CREATE_STATION = 'CREATE_STATION';

export const PUSH_SELECTED_BY_PRODUCT_STATIONS = 'PUSH_SELECTED_BY_PRODUCT_STATIONS';
export const PUSH_SELECTED_BY_REGION_STATIONS = 'PUSH_SELECTED_BY_REGION_STATIONS';

export const UPDATE_STATION_DONE = 'UPDATE_STATION_DONE';