export const SWITCH_ON_REGION_TABLE_VISIBILITY = 'SWITCH_ON_REGION_TABLE_VISIBILITY';

export const GET_ALL_REGIONS = 'GET_ALL_REGIONS';

export const PUSH_SELECTED_REGION_ID = 'PUSH_SELECTED_REGION_ID';
export const DELETE_SELECTED_REGION_ID = 'DELETE_SELECTED_REGION_ID';