export const SWITCH_ON_REGION_TABLE_VISIBILITY = 'SWITCH_ON_REGION_TABLE_VISIBILITY';

export const GET_ALL_REGIONS = 'GET_ALL_REGIONS';

export const PUSH_SELECTED_REGIONS_ID = 'PUSH_SELECTED_REGIONS_ID';

export const INC_REGION_COLOR_INDEX = 'INC_REGION_COLOR_INDEX';