export const SWITCH_ON_PRODUCT_TABLE_VISIBILITY = 'SWITCH_ON_PRODUCT_TABLE_VISIBILITY';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const PUSH_SELECTED_PRODUCT_ID = 'PUSH_SELECTED_PRODUCT_ID';
export const DELETE_SELECTED_PRODUCT_ID = 'DELETE_SELECTED_PRODUCT_ID';